version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:10.14.0
commands:
  preprocess:
    description: 'パッケージのインストールやビルドを行う'
    steps:
      - run: yarn install
      - run: yarn build
jobs:
  build:
    executor: node
    steps:
      - checkout
      - preprocess
      - run: echo "Build done!"
  test:
    executor: node
    steps:
      - checkout
      - preprocess
      - run: yarn test

workflows:
  version: 2
  built-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
