version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:10.14.0
jobs:
  build:
    executor: node
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: echo "hello world"
  test:
    executor: node
    steps:
      - run: yarn test

workflows:
  version: 2
  built-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
