version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:10.14.0
jobs:
  build:
    executor: node
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: echo "hello world"
      - run: yarn test
